version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: audio_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - AZURE_SPEECH_REGION=australiaeast
      - AZURE_STORAGE_CONTAINER=uploads
      - DB_NAME=audio_app
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    restart: always
    depends_on:
      - db

  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
