// app/transcribe/mockLongTranscriptionData.ts

export const mockLongTranscriptionData = [
  { start: 0.0, end: 10.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 10.0, end: 20.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 20.0, end: 30.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 30.0, end: 40.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 40.0, end: 50.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 50.0, end: 60.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 60.0, end: 70.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 70.0, end: 80.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 80.0, end: 90.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 90.0, end: 100.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 100.0, end: 110.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 110.0, end: 120.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 120.0, end: 130.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 130.0, end: 140.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 140.0, end: 150.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 150.0, end: 160.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 160.0, end: 170.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 170.0, end: 180.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 180.0, end: 190.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 190.0, end: 200.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 200.0, end: 210.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 210.0, end: 220.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 220.0, end: 230.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 230.0, end: 240.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 240.0, end: 250.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 250.0, end: 260.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 260.0, end: 270.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 270.0, end: 280.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 280.0, end: 290.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 290.0, end: 300.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 300.0, end: 310.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 310.0, end: 320.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 320.0, end: 330.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 330.0, end: 340.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 340.0, end: 350.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 350.0, end: 360.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 360.0, end: 370.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 370.0, end: 380.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 380.0, end: 390.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 390.0, end: 400.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 400.0, end: 410.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 410.0, end: 420.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 420.0, end: 430.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 430.0, end: 440.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 440.0, end: 450.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 450.0, end: 460.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 460.0, end: 470.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 470.0, end: 480.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 480.0, end: 490.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 490.0, end: 500.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 500.0, end: 510.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 510.0, end: 520.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 520.0, end: 530.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 530.0, end: 540.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 540.0, end: 550.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 550.0, end: 560.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 560.0, end: 570.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 570.0, end: 580.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 580.0, end: 590.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 590.0, end: 605.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 605.0, end: 615.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 610.0, end: 620.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 620.0, end: 630.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 630.0, end: 640.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 640.0, end: 650.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 650.0, end: 660.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 660.0, end: 670.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 670.0, end: 680.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 680.0, end: 690.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 690.0, end: 700.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 700.0, end: 710.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 710.0, end: 720.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 720.0, end: 730.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 730.0, end: 740.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 740.0, end: 750.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 750.0, end: 760.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 760.0, end: 770.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 770.0, end: 780.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 780.0, end: 790.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 790.0, end: 800.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 800.0, end: 810.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 810.0, end: 820.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 820.0, end: 830.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 830.0, end: 840.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 840.0, end: 850.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 850.0, end: 860.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 860.0, end: 870.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 870.0, end: 880.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 880.0, end: 890.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 890.0, end: 900.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 900.0, end: 910.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 910.0, end: 920.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 920.0, end: 930.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 930.0, end: 940.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 940.0, end: 950.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 950.0, end: 960.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 960.0, end: 970.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 970.0, end: 980.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 980.0, end: 990.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 990.0, end: 1000.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1000.0, end: 1010.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1010.0, end: 1020.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1020.0, end: 1030.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1030.0, end: 1040.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 1040.0, end: 1050.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1050.0, end: 1060.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1060.0, end: 1070.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1070.0, end: 1080.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1080.0, end: 1090.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1090.0, end: 1100.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1100.0, end: 1110.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1110.0, end: 1120.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1120.0, end: 1130.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1130.0, end: 1140.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1140.0, end: 1150.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1150.0, end: 1160.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1160.0, end: 1170.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1170.0, end: 1180.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1180.0, end: 1190.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1190.0, end: 1200.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 1200.0, end: 1210.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1210.0, end: 1220.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1220.0, end: 1230.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1230.0, end: 1240.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1240.0, end: 1250.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1250.0, end: 1260.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1260.0, end: 1270.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1270.0, end: 1280.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1280.0, end: 1290.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1290.0, end: 1300.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1300.0, end: 1310.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1310.0, end: 1320.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1320.0, end: 1330.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1330.0, end: 1340.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1340.0, end: 1350.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1350.0, end: 1360.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1360.0, end: 1370.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1370.0, end: 1380.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1380.0, end: 1390.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 1390.0, end: 1400.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1400.0, end: 1410.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 1410.0, end: 1420.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1420.0, end: 1430.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1430.0, end: 1440.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1440.0, end: 1450.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1450.0, end: 1460.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1460.0, end: 1470.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1470.0, end: 1480.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1480.0, end: 1490.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1490.0, end: 1500.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1500.0, end: 1510.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1510.0, end: 1520.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1520.0, end: 1530.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1530.0, end: 1540.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1540.0, end: 1550.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1550.0, end: 1560.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1560.0, end: 1570.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1570.0, end: 1580.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1580.0, end: 1590.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1590.0, end: 1600.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1600.0, end: 1610.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1610.0, end: 1620.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1620.0, end: 1630.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1630.0, end: 1640.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1640.0, end: 1650.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1650.0, end: 1660.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1660.0, end: 1670.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1670.0, end: 1680.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1680.0, end: 1690.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1690.0, end: 1700.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1700.0, end: 1710.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1710.0, end: 1720.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1720.0, end: 1730.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1730.0, end: 1740.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 1740.0, end: 1750.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1750.0, end: 1760.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1760.0, end: 1770.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1770.0, end: 1780.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1780.0, end: 1790.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1790.0, end: 1800.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1800.0, end: 1810.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1810.0, end: 1820.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1820.0, end: 1830.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1830.0, end: 1840.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1840.0, end: 1850.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1850.0, end: 1860.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1860.0, end: 1870.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 1870.0, end: 1880.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 1880.0, end: 1890.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 1890.0, end: 1900.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1900.0, end: 1910.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 1910.0, end: 1920.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1920.0, end: 1930.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1930.0, end: 1940.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1940.0, end: 1950.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 1950.0, end: 1960.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1960.0, end: 1970.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 1970.0, end: 1980.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 1980.0, end: 1990.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 1990.0, end: 2000.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2000.0, end: 2010.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2010.0, end: 2020.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2020.0, end: 2030.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2030.0, end: 2040.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2040.0, end: 2050.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2050.0, end: 2060.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2060.0, end: 2070.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2070.0, end: 2080.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2080.0, end: 2090.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2090.0, end: 2100.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2100.0, end: 2110.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2110.0, end: 2120.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2120.0, end: 2130.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2130.0, end: 2140.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2140.0, end: 2150.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2150.0, end: 2160.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2160.0, end: 2170.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2170.0, end: 2180.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2180.0, end: 2190.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2190.0, end: 2200.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2200.0, end: 2210.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2210.0, end: 2220.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2220.0, end: 2230.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2230.0, end: 2240.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2240.0, end: 2250.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2250.0, end: 2260.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2260.0, end: 2270.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2270.0, end: 2280.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2280.0, end: 2290.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2290.0, end: 2300.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2300.0, end: 2310.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2310.0, end: 2320.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2320.0, end: 2330.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2330.0, end: 2340.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2340.0, end: 2350.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2350.0, end: 2360.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2360.0, end: 2370.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2370.0, end: 2380.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2380.0, end: 2390.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2390.0, end: 2400.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2400.0, end: 2410.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2410.0, end: 2420.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2420.0, end: 2430.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2430.0, end: 2440.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2440.0, end: 2450.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2450.0, end: 2460.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2460.0, end: 2470.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2470.0, end: 2480.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2480.0, end: 2490.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2490.0, end: 2500.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2500.0, end: 2510.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2510.0, end: 2520.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2520.0, end: 2530.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2530.0, end: 2540.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2540.0, end: 2550.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2550.0, end: 2560.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2560.0, end: 2570.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2570.0, end: 2580.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2580.0, end: 2590.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2590.0, end: 2600.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2600.0, end: 2610.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2610.0, end: 2620.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2620.0, end: 2630.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2630.0, end: 2640.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2640.0, end: 2650.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2650.0, end: 2660.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2660.0, end: 2670.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2670.0, end: 2680.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2680.0, end: 2690.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2690.0, end: 2700.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2700.0, end: 2710.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2710.0, end: 2720.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2720.0, end: 2730.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2730.0, end: 2740.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2740.0, end: 2750.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2750.0, end: 2760.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 2760.0, end: 2770.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2770.0, end: 2780.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2780.0, end: 2790.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2790.0, end: 2800.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2800.0, end: 2810.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2810.0, end: 2820.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2820.0, end: 2830.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 2830.0, end: 2840.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2840.0, end: 2850.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2850.0, end: 2860.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 2860.0, end: 2870.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2870.0, end: 2880.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 2880.0, end: 2890.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2890.0, end: 2900.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2900.0, end: 2910.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 2910.0, end: 2920.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 2920.0, end: 2930.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2930.0, end: 2940.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2940.0, end: 2950.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2950.0, end: 2960.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 2960.0, end: 2970.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 2970.0, end: 2980.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 2980.0, end: 2990.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 2990.0, end: 3000.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3000.0, end: 3010.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3010.0, end: 3020.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3020.0, end: 3030.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3030.0, end: 3040.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3040.0, end: 3050.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3050.0, end: 3060.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3060.0, end: 3070.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 3070.0, end: 3080.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3080.0, end: 3090.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3090.0, end: 3100.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3100.0, end: 3110.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3110.0, end: 3120.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3120.0, end: 3130.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3130.0, end: 3140.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3140.0, end: 3150.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3150.0, end: 3160.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3160.0, end: 3170.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3170.0, end: 3180.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3180.0, end: 3190.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3190.0, end: 3200.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3200.0, end: 3210.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3210.0, end: 3220.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3220.0, end: 3230.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3230.0, end: 3240.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3240.0, end: 3250.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3250.0, end: 3260.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3260.0, end: 3270.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3270.0, end: 3280.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3280.0, end: 3290.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3290.0, end: 3300.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 3300.0, end: 3310.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3310.0, end: 3320.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3320.0, end: 3330.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 3330.0, end: 3340.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 3340.0, end: 3350.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3350.0, end: 3360.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3360.0, end: 3370.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3370.0, end: 3380.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3380.0, end: 3390.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3390.0, end: 3400.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3400.0, end: 3410.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3410.0, end: 3420.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3420.0, end: 3430.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3430.0, end: 3440.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3440.0, end: 3450.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3450.0, end: 3460.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3460.0, end: 3470.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3470.0, end: 3480.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3480.0, end: 3490.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3490.0, end: 3500.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3500.0, end: 3510.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 3510.0, end: 3520.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3520.0, end: 3530.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3530.0, end: 3540.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3540.0, end: 3550.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3550.0, end: 3560.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3560.0, end: 3570.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3570.0, end: 3580.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3580.0, end: 3590.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3590.0, end: 3600.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3600.0, end: 3610.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3610.0, end: 3620.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3620.0, end: 3630.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3630.0, end: 3640.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3640.0, end: 3650.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3650.0, end: 3660.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3660.0, end: 3670.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3670.0, end: 3680.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3680.0, end: 3690.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 3690.0, end: 3700.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3700.0, end: 3710.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3710.0, end: 3720.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3720.0, end: 3730.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3730.0, end: 3740.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3740.0, end: 3750.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 3750.0, end: 3760.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3760.0, end: 3770.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3770.0, end: 3780.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3780.0, end: 3790.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3790.0, end: 3800.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 3800.0, end: 3810.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3810.0, end: 3820.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3820.0, end: 3830.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 3830.0, end: 3840.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3840.0, end: 3850.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 3850.0, end: 3860.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3860.0, end: 3870.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 3870.0, end: 3880.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3880.0, end: 3890.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3890.0, end: 3900.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 3900.0, end: 3910.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 3910.0, end: 3920.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3920.0, end: 3930.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 3930.0, end: 3940.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 3940.0, end: 3950.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3950.0, end: 3960.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3960.0, end: 3970.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 3970.0, end: 3980.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 3980.0, end: 3990.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 3990.0, end: 4000.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4000.0, end: 4010.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4010.0, end: 4020.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4020.0, end: 4030.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4030.0, end: 4040.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4040.0, end: 4050.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4050.0, end: 4060.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 4060.0, end: 4070.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 4070.0, end: 4080.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4080.0, end: 4090.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4090.0, end: 4100.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4100.0, end: 4110.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4110.0, end: 4120.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4120.0, end: 4130.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4130.0, end: 4140.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4140.0, end: 4150.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4150.0, end: 4160.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4160.0, end: 4170.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4170.0, end: 4180.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4180.0, end: 4190.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4190.0, end: 4200.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4200.0, end: 4210.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4210.0, end: 4220.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4220.0, end: 4230.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4230.0, end: 4240.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4240.0, end: 4250.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4250.0, end: 4260.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4260.0, end: 4270.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4270.0, end: 4280.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 4280.0, end: 4290.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4290.0, end: 4300.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4300.0, end: 4310.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4310.0, end: 4320.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4320.0, end: 4330.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4330.0, end: 4340.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4340.0, end: 4350.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4350.0, end: 4360.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4360.0, end: 4370.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4370.0, end: 4380.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4380.0, end: 4390.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4390.0, end: 4400.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4400.0, end: 4410.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4410.0, end: 4420.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4420.0, end: 4430.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4430.0, end: 4440.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4440.0, end: 4450.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4450.0, end: 4460.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4460.0, end: 4470.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 4470.0, end: 4480.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4480.0, end: 4490.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 4490.0, end: 4500.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 4500.0, end: 4510.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4510.0, end: 4520.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4520.0, end: 4530.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4530.0, end: 4540.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 4540.0, end: 4550.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4550.0, end: 4560.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4560.0, end: 4570.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4570.0, end: 4580.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4580.0, end: 4590.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 4590.0, end: 4600.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4600.0, end: 4610.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4610.0, end: 4620.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4620.0, end: 4630.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4630.0, end: 4640.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4640.0, end: 4650.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4650.0, end: 4660.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4660.0, end: 4670.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4670.0, end: 4680.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4680.0, end: 4690.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4690.0, end: 4700.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4700.0, end: 4710.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 4710.0, end: 4720.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4720.0, end: 4730.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4730.0, end: 4740.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4740.0, end: 4750.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4750.0, end: 4760.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4760.0, end: 4770.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4770.0, end: 4780.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4780.0, end: 4790.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4790.0, end: 4800.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4800.0, end: 4810.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 4810.0, end: 4820.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4820.0, end: 4830.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4830.0, end: 4840.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 4840.0, end: 4850.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 4850.0, end: 4860.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4860.0, end: 4870.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4870.0, end: 4880.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4880.0, end: 4890.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 4890.0, end: 4900.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 4900.0, end: 4910.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 4910.0, end: 4920.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4920.0, end: 4930.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 4930.0, end: 4940.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4940.0, end: 4950.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4950.0, end: 4960.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 4960.0, end: 4970.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 4970.0, end: 4980.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 4980.0, end: 4990.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 4990.0, end: 5000.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5000.0, end: 5010.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 5010.0, end: 5020.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 5020.0, end: 5030.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 5030.0, end: 5040.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 5040.0, end: 5050.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 5050.0, end: 5060.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 5060.0, end: 5070.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 5070.0, end: 5080.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5080.0, end: 5090.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 5090.0, end: 5100.0, text: "Artificial intelligence is transforming industries worldwide, from healthcare to finance." },
  { start: 5100.0, end: 5110.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 5110.0, end: 5120.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 5120.0, end: 5130.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5130.0, end: 5140.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 5140.0, end: 5150.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 5150.0, end: 5160.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 5160.0, end: 5170.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 5170.0, end: 5180.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 5180.0, end: 5190.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
  { start: 5190.0, end: 5200.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 5200.0, end: 5210.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 5210.0, end: 5220.0, text: "Machine learning enables computers to learn from data and make predictions or decisions." },
  { start: 5220.0, end: 5230.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5230.0, end: 5240.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 5240.0, end: 5250.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 5250.0, end: 5260.0, text: "AI in healthcare can assist with diagnosis, treatment planning, and patient monitoring." },
  { start: 5260.0, end: 5270.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5270.0, end: 5280.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5280.0, end: 5290.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 5290.0, end: 5300.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 5300.0, end: 5310.0, text: "It's essential to develop AI systems that are fair, accountable, and explainable." },
  { start: 5310.0, end: 5320.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 5320.0, end: 5330.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 5330.0, end: 5340.0, text: "Natural language processing allows AI to understand and generate human language." },
  { start: 5340.0, end: 5350.0, text: "AI is revolutionizing the way we interact with technology in our daily lives." },
  { start: 5350.0, end: 5360.0, text: "Deep learning models use neural networks with many layers to achieve high accuracy." },
  { start: 5360.0, end: 5370.0, text: "AI-powered recommendation systems are used by platforms like Netflix and Amazon." },
  { start: 5370.0, end: 5380.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 5380.0, end: 5390.0, text: "Ethical considerations in AI include data privacy, algorithmic bias, and transparency." },
  { start: 5390.0, end: 5400.0, text: "Autonomous vehicles rely heavily on real-time data processing and computer vision." },
];